name: Main

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.elm
          key: ${{ runner.os }}-modules-${{ hashFiles('**/elm.json') }}
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/02ac89b8e803.tar.gz
      - uses: cachix/cachix-action@v10
        with:
          name: elm-robots-humans
          signingKey: ${{secrets.CACHIX_SIGNIN_KEY}}
          authToken: ${{secrets.CACHIX_AUTH_TOKEN}}
      - name: Run tests
        run: nix-shell --run "elm-coverage"
