name: Main

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.elm
          key: ${{ runner.os }}-${{ hashFiles('**/elm.json') }}
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/02ac89b8e803.tar.gz
      - uses: cachix/cachix-action@v12
        with:
          name: elm-robots-humans
          authToken: ${{secrets.CACHIX_AUTH_TOKEN}}
      - name: Run tests
        run: nix-shell --run "elm-coverage"
      - name: Make build
        run: nix-shell --run "elm make --output /dev/null"
      - name: Make docs
        run: nix-shell --run "elm make --docs docs.json"

  publish:
    name: publish
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.elm
          key: ${{ runner.os }}-${{ hashFiles('**/elm.json') }}
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/02ac89b8e803.tar.gz
      - uses: cachix/cachix-action@v12
        with:
          name: elm-robots-humans
          authToken: ${{secrets.CACHIX_AUTH_TOKEN}}
      - name: Publish package
        uses: dillonkearns/elm-publish-action@1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}